name: Release Chart

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'The version of release chart'
        required: true
        default: ''
  release:
    types:
      - published

env:
  RELEASE_VERSION: ${{ github.ref_name }}

run-name: release chart ${{ inputs.release_version }} ${{ github.ref_name }}

jobs:
  release-version:
    runs-on: ubuntu-latest
    outputs:
      release-version: ${{ steps.get_release_version.outputs.release_version }}
    steps:
      - name: Get Release Version
        id: get_release_version
        run: |
          RELEASE_VERSION=${{ inputs.release_version }}
          if [ -z "$RELEASE_VERSION" ]; then
              RELEASE_VERSION=${{ env.RELEASE_VERSION }}
          fi
          echo release_version=$RELEASE_VERSION >> $GITHUB_OUTPUT

  release-chart:
    needs: release-version
    uses: apecloud/apecloud-cd/.github/workflows/release-charts.yml@v0.1.55
    with:
      VERSION: "${{ needs.release-version.outputs.release-version }}"
      CHART_NAME: "k8s-mcp-server"
      CHART_DIR: "deploy"
      APECD_REF: "v0.1.55"
    secrets: inherit

  release-message:
    runs-on: ubuntu-latest
    needs: [ release-chart ]
    outputs:
      content-result: ${{ steps.release_message.outputs.content_result }}
    if: ${{ always() && github.event.action == 'published' }}
    steps:
      - uses: actions/checkout@v4
      - name: release message
        id: release_message
        run: |
          CONTENT="error"
          if [[ "${{ needs.release-chart.result }}" == "success" ]]; then
              CONTENT="success"
          fi
          echo 'content_result='$CONTENT >> $GITHUB_OUTPUT

  send-message:
    needs: [ release-version, release-message ]
    if: ${{ always() && github.event.action == 'published' }}
    uses: apecloud/apecloud-cd/.github/workflows/feishui-message.yml@v0.1.55
    with:
      TYPE: "2"
      CONTENT: "release k8s-mcp-server chart ${{ needs.release-version.outputs.release-version }} ${{ needs.release-message.outputs.content-result }}"
      APECD_REF: "v0.1.55"
    secrets: inherit